apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-pod-not-ready
  namespace: metrics
spec:
  groups:
  - name: nodes
    rules:
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
      for: 1m
      labels:
        severity: critical

    - alert: TooManyNodes
      expr: count(kube_node_info) > 3
      for: 15m
      labels:
        severity: notify
      annotations:
        summary: Cluster increased
        description: The number of the nodes in the cluster increased
    - alert: TooFewNodes
      expr: count(kube_node_info) < 1
      for: 15m
      labels:
        severity: notify
      annotations:
        summary: Cluster decreased
        description: The number of the nodes in the cluster decreased
