apiVersion: v1
kind: Namespace
metadata:
  name: staging

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: staging
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /demo
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port:
              number: 8080

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
  namespace: staging

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db
subjects:
- kind: ServiceAccount
  name: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: staging
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      serviceAccountName: db
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mongo:3.3
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        resources:
          limits:
            memory: "550Mi"
            cpu: 0.2
          requests:
            memory: "500Mi"
            cpu: 0.1
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      - name: db-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: "app=db"
        - name: KUBE_NAMESPACE
          value: staging
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: db
        resources:
          limits:
            memory: "550Mi"
            cpu: 0.2
          requests:
            memory: "550Mi"
            cpu: 0.1
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany  # RWX required for multiple Pods to use the same PV
      resources:
        requests:
          storage: 4Gi
      volumeName: local-pv  # Bind this PVC to the manually created PV

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: staging
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: db

# ---

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: db
#   namespace: staging
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: StatefulSet
#     name: db
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 80
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-5
        env:
        - name: DB
          value: db
        readinessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          initialDelaySeconds: 30
        resources:
          limits:
            memory: 1.5Gi
            cpu: 0.1
          requests:
            memory: 1Gi
            cpu: 0.01

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: staging
spec:
  ports:
  - port: 8080
  selector:
    app: api





# ---

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: api
#   namespace: staging
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: api
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 80
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 80
